name: Node CI

on:
- pull_request
- push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install node_modules
      run: |
        npm ci

    - name: Lint the code
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm test
      env:
        NODE_ENV: test

    - name: Build site
      run: |
        npm run build
